### ISSUE TITLE
[TASK] Sprint1_FE_프로젝트작성_와이어프레임

### ISSUE THREAD

**Issue by seongjinpark1** [codestates/JISIK-SPONSOR#14]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 프로젝트 작성페이지 와이어프레임 구현

### **TODO**

- [x]  기본정보 페이지 와이어프레임 구현
- [x]  예산정보 페이지 와이어프레임 구현
- [x] 상세내용 페이지 와이어프레임 구현
- [x] 팀소개 페이지 와이어프레임 구현

### **Labels**

- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
