### ISSUE TITLE
[TASK] SR_프로젝트 기획 및 범위설정

### ISSUE THREAD

**Issue by LuckyTW** [codestates/JISIK-SPONSOR#2]
### **ISSUE**

- Group: `sr`
- Type: `feature`
- Detail: 프로젝트 기획 및 범위 설정/ 팀 미팅

### **TODO**

- [x]  아이디어 브레인 스토밍
- [x]  아이템 선정 및 기능 리스트업
- [x]  프로젝트(서비스)명 정하기 

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 4h`
- Group : `both`
- Sprint: `SR 기획 및 WIKI 작성`
- Urgency: `High`
