### ISSUE TITLE
[TASK] Sprint1_FE_프로젝트 작성_기본 정보 기능구현

### ISSUE THREAD

**Issue by seongjinpark1** [codestates/JISIK-SPONSOR#21]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 해쉬태그 추가기능, 표지이미지 추가 기능, 인풋 포커스시에 메세지 구현

### **TODO**

- [x]  해쉬태그 추가 기능 구현
- [x]  표지이미지 추가 기능 구현
- [x] 인풋 포커스시에 메세지 기능 구현

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
