### ISSUE TITLE
[TASK] Sprint1_FE_프로젝트 작성_예산 정보 기능 구현

### ISSUE THREAD

**Issue by seongjinpark1** [codestates/JISIK-SPONSOR#23]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 예산 항목 추가 기능 구현, 펀딩 총액 계산, 인풋 포커스시 메세지 구현

### **TODO**

- [x]  예산 항목 추가 기능 구현
- [x]  펀딩 총액 계산 구현
- [x] 인풋 포커스시 메세지 구현

### **Labels**

- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
