### ISSUE TITLE
[TASK] Sprint1_FE_프로젝트 작성_상세 내용 기능 구현

### ISSUE THREAD

**Issue by seongjinpark1** [codestates/JISIK-SPONSOR#25]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 일정 항목 추가 기능 구현, 목표날짜 달력 구현(or 라이브러리사용), 인풋 포커스시 메세지 기능 구현

### **TODO**

- [x]  일정 항목 추가 기능 구현,
- [x]  목표날짜 달력 구현(or 라이브러리사용)
- [x] 인풋 포커스시 메세지 기능 구현

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
