### ISSUE TITLE
[TASK] Sprint1_FE_프로젝트 작성_팀 소개 기능 구현

### ISSUE THREAD

**Issue by seongjinpark1** [codestates/JISIK-SPONSOR#27]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 팀원 추가 기능 구현, 팀 대표이미지 추가 기능 구현, 인풋 포커스시 메시지 기능 구현

### **TODO**

- [x]  팀원 추가 기능 구현
- [x]  팀 대표이미지 추가 기능 구현
- [x] 인풋 포커스시 메시지 기능 구현

### **Labels**

- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
