### ISSUE TITLE
[TASK] Sprint1_FE_마이페이지_API 요청

### ISSUE THREAD

**Issue by LuckyTW** [codestates/JISIK-SPONSOR#30]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 마이페이지 화면에 필요한 API 요청 구현

### **TODO**

- [ ]  나의 프로젝트 조회 & 리다이렉트
- [ ]  후원한 프로젝트 조회  & 리다이렉트
- [ ] 즐겨찾기 조회 & 해제 & 리다이렉트
- [ ] 내가 쓴 댓글 조회 & 리다이렉트

### **Labels**

- Estimated time: `E: 12h`
- Group : `client`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `High`, `Middle`, `Low`
