### ISSUE TITLE
[TASK] Sprint2_BE_도메인 구매 및 HTTPS 배포

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#32]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 도메인 구매 및 HTTPS 배포

### **TODO**

- [x] 도메인 구매
- [x] AWS 도메인 연결 (클라이언트, 서버)
- [x] AWS 클라이언트 HTTPS 구현
- [x] AWS 서버 HTTPS 구현 (로드 벨런싱)

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint2_Advanced`
- Urgency: `Middle`
