### ISSUE TITLE
[TASK] Sprint1_BE_서버 세팅 (클라이언트, 서버, 데이터베이스)

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#33]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 서버 세팅 (클라이언트, 서버, 데이터베이스)

### **TODO**

- [x] 클라이언트 S3 버킷 세팅
- [x] 서버 EC2 인스턴스 세팅
- [x] 데이터베이스 RDS 세팅

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Low`
