### ISSUE TITLE
[TASK] Sprint1_BE_Sequelize 세팅 (모델 및 시드 생성, 관계 설정)

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#35]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: Sequelize 세팅 (모델 및 시드 생성, 관계 설정)

### **TODO**

- [x] Sequelize 세팅 (모델 생성)
- [x] Sequelize 세팅 (시드 생성)
- [x] Sequelize 세팅 (관계 설정)

### **Labels**

- Estimated time: `E: 8h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Low`
