### ISSUE TITLE
[TASK] Sprint1_BE_인증 및 권한 부여 (JWT 토큰 인증 방식)

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#36]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 인증 및 권한 부여 (JWT 토큰 인증 방식)

### **TODO**

- [x] JWT 토큰 인증 구현
- [x] 일반 회원, 관리자 인증 검사 구현
- [x] [POST] 로그인 API
- [x] [POST] 로그아웃 API
- [x] [POST] 회원가입 API

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
