### ISSUE TITLE
[TASK] Sprint1_BE_사용자 CRUD API

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#37]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 사용자 CRUD API

### **TODO**

- [x] [GET] 로그인 여부 조회
- [x] [GET] 사용자 공개 프로필 조회
- [x] [GET] 현재 로그인한 사용자 정보 조회
- [x] [GET] 현재 로그인한 사용자 알람
- [x] [POST] 프로필 이미지 업로드
- [x] [PATCH] 사용자 정보 변경
- [x] [DELETE] 회원 탈퇴

### **Labels**

- Estimated time: `E: 6h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
