### ISSUE TITLE
[TASK] Sprint1_BE_프로젝트 CRUD API

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#38]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 프로젝트 CRUD API

### **TODO**

- [x] [GET] 여러 프로젝트 조회
- [x] [GET] 특정 프로젝트 조회
- [x] [POST] 프로젝트 생성
- [x] [POST] 썸네일 이미지 업로드
- [x] [PATCH] 프로젝트 수정
- [x] [PATCH] 프로젝트 승인
- [x] [DELETE] 프로젝트 삭제

### **Labels**

- Estimated time: `E: 16h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
