### ISSUE TITLE
[TASK] Sprint1_BE_테스트가 필요한 기능 스몰 테스트

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#42]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 테스트가 필요한 기능 스몰 테스트

### **TODO**

- [x]  이미지 업로드 시 S3 클라우드 사용법 (aws-sdk + multer + multer-s3)
- [x]  이메일 보내는 방법 (nodemailer)
- [x]  스케쥴에 의한 이벤트 처리하는 방법 (node-schedule)
- [x]  이메일 템플릿 만드는 방법 (pug HTML 템플릿 엔진 + nodemailer)
- [x]  회원가입 시 이메일 인증 하는 법 (nodemailer + crypto)
### **Labels**

- Estimated time: `E: 12h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `High`
