### ISSUE TITLE
[TASK] Sprint2_BE_서버 배포 자동화 설정

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#43]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 서버 배포 자동화 설정

### **TODO**

- [x] AWS parameter store 환경변수 등록
- [x] AWS appscript / appspec 세팅
- [x] AWS codePipe 생성

### **Labels**

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint2_Advanced`
- Urgency: `Middle`
