### ISSUE TITLE
[TASK] Sprint1_BE_찜 CRD API

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#63]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 프로젝트 찜 CRD API

### **TODO**

- [x] [GET] 현재 사용자의 특정 프로젝트 찜 여부
- [x] [POST] 현재 사용자의 특정 프로젝트 찜하기
- [x] [DELET] 현재 사용자의 특정 프로젝트 찜 취소

### **Labels**

- Estimated time: `E: 4h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Middle`
