### ISSUE TITLE
[TASK] Sprint1_BE_주문 생성 및 결제 검증 API

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#64]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 주문 생성 및 결제 검증 API

### **TODO**

- [x] [GET] 특정 사용자의 모든 주문 조회
- [x] [POST] 주문 생성
- [x] [POST] 결제 정보 검증 및 저장

### **Labels**

- Estimated time: `E: 4h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `Hi`
