### ISSUE TITLE
[TASK] Sprint1_BE_팀원 항목 CUD API

### ISSUE THREAD

**Issue by hanamon** [codestates/JISIK-SPONSOR#68]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: 프로젝트 팀원 항목 CUD API

### **TODO**

- [x] [POST] 팀원 항목 생성
- [x] [PATCH] 팀원 항목 수정
- [x] [DELETE] 팀원 항목 삭제

### **Labels**

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint1_Bare-Minimum`
- Urgency: `High`
